# Generated by Django 5.0.7 on 2024-12-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="section",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C")], max_length=1, null=True
            ),
        ),
    ]
