# Generated by Django 5.0.7 on 2024-09-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_people_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="birthday_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="people",
            name="passport_data",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
