# Generated by Django 5.0.7 on 2024-09-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_seat_images_delete_seatimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/people/"),
        ),
    ]
