# Generated by Django 5.0.7 on 2024-09-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_people_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seat",
            old_name="images",
            new_name="image",
        ),
    ]
