# Generated by Django 5.0.7 on 2024-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_images_seat_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="image",
            field=models.ImageField(
                default="images/people/default_user.jpg", upload_to="images/people/"
            ),
        ),
    ]
