# Generated by Django 5.0.7 on 2024-09-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_people_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="image",
            field=models.ImageField(
                default="images/no_image.png", upload_to="images/seats/"
            ),
        ),
    ]
