# Generated by Django 5.0.7 on 2024-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_seat_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="image",
            field=models.ImageField(
                blank=True,
                default="images/people/default_user.jpg",
                upload_to="images/people/",
            ),
        ),
        migrations.AlterField(
            model_name="seat",
            name="image",
            field=models.ImageField(
                blank=True, default="images/no_image.png", upload_to="images/seats/"
            ),
        ),
    ]
