# Generated by Django 5.0.7 on 2024-09-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_people_image_alter_seat_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="has_taken",
            field=models.BooleanField(default=False),
        ),
    ]
