# Generated by Django 5.0.7 on 2024-10-21 15:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_seat_has_taken"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="core.seat",
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="ID",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=40,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
